sebMar92/e-commerce-frontend

client/src/components/CardCart.js
client/src/components/Cart.js

Card de producto en el Carrito de compras

---

client/src/components/CardHome.js

se modifico el tamaño de las cardHome

---

client/src/components/Pagination.js
client/src/components/ProductsByCategory.js

Se creo el componente paginado de front, solo muestra forzadamente los botones necesarios para navegar por la pagina!
Faltan funcionalidades.
Se integro al componente de productos donde se debe mostrar.

PaginadoFront

---

client/package.json
client/src/Redux/Actions/actions.js
client/src/Redux/Actions/types.js
client/src/Redux/Reducers/HomeReducer.js
client/src/components/commons/SearchBar.js

Primera parte del Search bar, 
podes en este momento buscar por nombre de producto y te lo va a ir autocompletando, falta terminar css y que te muestre por categorias y otras cosas, lo pusheo antes de que lo vuelva a borrar :v jaja

searchbar-firstpart

---

client/src/components/ProductDetails.js

Diseño para móviles hasta 640px

Mobile design

---

client/src/App.js
client/src/Redux/Actions/actions.js
client/src/Redux/Reducers/CategoriesReducer.js
client/src/Redux/Reducers/HomeReducer.js
client/src/Redux/Store/Store.js
client/src/components/Card.js
client/src/components/CarouselCateg.js
client/src/components/DropDownCategories.js
client/src/components/NavBar.js
client/src/components/Pagination.js
client/src/components/ProductsByCategory.js

Se creo un sistema de manejo de querys en la URL para despachar las acciones correspondientes y traer los datos necesarios.
Se agrego un componente particular para el dropdwon de categories.
Se renderizo todo lo necesario en la pagina products.
Se modifico el reducer de Home.
Se modifico la Accion de getProducts para trabajarla con querys. 
Se le aplico al componente card las props necesaira para empezar a mostrar datos en la ruta.
Se agrego funcionalidad a los botones del paginado.
IMPORTANTE: Revisar la nueva accion de getProducts porque vamos a trabajar de esta nueva manera a traves de querys para modificar la URL. Y tambien revisar la funcionalidad de manejo de querys.

Component catalogo complete

---

client/src/components/DropDownCategories.js
client/src/components/FilterAndOrden.js
client/src/components/Pagination.js
client/src/components/commons/useURLqueries.js

Se agregó un custom hook en utils para simplificar la nueva funcionalidad que maneja el dispatch con la URL del front (useURLquery). Devuelve un objeto con key-values igual a las queries del url.
Ejemplo: 
localhost:3000/products?categoryId=5&freeShipping=true&order=ASC => {categoryId: 5, freeShipping: "true", order: "ASC"}
Se agregó funcionalidad al filtro por envío gratis, por inputs de precio mínimo y máximo, y al ordenado ascendiente y descendiente. (Pendiente agregar función a los botones fijos de mayor y menor a un precio).

almost all filters working

---

client/src/Redux/Actions/actions.js
client/src/components/CardHome.js
client/src/components/CarouselCateg.js
client/src/components/CarouselPromo.js
client/src/components/Home.js

ya estan hechos los carruseles que renderizan en home: tres categorias al azar con sus productos y el enlace a la ruta de cada detalle del producto. Falta cuadrar los botones aunque ya son responsivos

carousel-march-19

---

client/public/index.html
client/public/manifest.json
client/src/components/CardHome.js
client/src/components/CarouselCateg.js
client/src/components/CarouselPromo.js
client/src/components/DropDown.js
client/src/components/DropDownCategories.js
client/src/components/Footer/FooterHome.js
client/src/components/NavBar.js

Detalles del home, limpieza de errores de consola.
Prototipo 1.

Detalles pulidos del Home Demo1

---

client/src/components/Card.js
client/src/components/DropDownCategories.js
client/src/components/FilterAndOrden.js
client/src/components/Pagination.js
client/src/components/ProductsByCategory.js
client/src/components/commons/SearchBar.js

New changes demo1

---

client/src/components/EmailVerification.js
client/src/components/LoginComponent.js
client/src/components/NavBarEmpty.js

Quick changes

---

client/src/Redux/Actions/actions.js
client/src/Redux/Actions/types.js
client/src/Redux/Reducers/HomeReducer.js
client/src/components/LoginComponent.js
client/src/components/NavBar.js
client/src/components/commons/LoginProfileButton.js

Hay una acción que utiliza el token de acceso de usuario, y que en caso de encontrarse con el token expirado usa el de refresco para conseguir uno nuevo, seguido repite el primer llamado pero con el token nuevo.
**Funciona, pero no esta bien hecho**. No lo pude hacer como se debe, después lo charlamos a ver si alguien logra investigar y hacerlo bien. Pero mientras tanto pueden usarlo de ejemplo para nuevas acciones así trabajan con la info del back sin relogear cada 15 min.
Necesitan tambien tener actualizado el back con el cambio que pusheó Fran hace unas horas.
Fuera de eso, agrega el boton de login/signup y perfil. Esta solo hecho el diseño, falta terminarlo y darle funcionalidad

Login profile button navbar

---

client/src/Redux/Actions/actions.js
client/src/Redux/Reducers/HomeReducer.js
client/src/components/CardCart.js
client/src/components/Cart.js
client/src/components/EditProducts.js

queda funcionando carrito mostrando los productos

se realiza get y se ajusta cart

---

client/src/Redux/Actions/actions.js
client/src/Redux/Actions/types.js
client/src/Redux/Reducers/ProductByIDReducer.js
client/src/components/Comment/CreateComment.js
client/src/components/Comment/ShowComment.js
client/src/components/ProductDetails/ProductDetails.js
client/src/components/ProductDetails/Slider.js

Posibilidad de crear, editar y eliminar un comentario existente.
Renderizar el comentario del usuario en el producto.
---- Pequeño Hotfix ------
Slider de detalle de producto arreglado.

CommentSection

---

client/src/Redux/Actions/actions.js
client/src/Redux/Actions/types.js
client/src/Redux/Reducers/HomeReducer.js
client/src/components/Card.js
client/src/components/CardHome.js
client/src/components/CarouselCateg.js
client/src/components/CarouselPromo.js
client/src/components/DropDownCategories.js
client/src/components/Home.js
client/src/components/LoginComponent.js
client/src/components/NavBar.js
client/src/components/ProductsByCategory.js
client/src/components/commons/CartModal.js
client/src/components/commons/FavsModal.js
client/src/components/commons/LoginProfileButton.js

Principalmete hago el PR para que todos trabajen con las actions nuevas, sigo trabajando en el carrito aunque ya se pueden agregar productos y ver en el desplegable, tanto desde categories como desde home. Empece a cambiar el diseño de la navbar y la idea seria optimizar todos los cambios que estoy haciendo para que queden andando para hoy.

Muchas cosas pero ninguna andando al 100%

---

client/src/Redux/Actions/actions.js

Por favor alta prioridad de aprobacion.

Se arreglo develop

---

client/src/Redux/Actions/actions.js
client/src/Redux/Actions/types.js
client/src/Redux/Reducers/HomeReducer.js
client/src/components/ActivateDiscounts.js
client/src/components/AdminAllProducts.js
client/src/components/AdminAllUsers.js
client/src/components/AdminProfile.js
client/src/components/CreateProducts.js
client/src/components/EmailVerification.js
client/src/components/ListOfOrders.js
client/src/components/LoginComponent.js
client/src/components/NavbarAdmin.js
client/src/components/NewsletterEdit.js
client/src/components/ProductDetails/ProductDetails.js
client/src/components/commons/ButtonBuy.js
client/src/components/commons/CartModal.js
client/src/components/commons/FavsModal.js

Cambie los botones de compra de details, modifique algunos estilos de la navbar, edite algunas rutas del admin (sigo con eso)

Modifique multples archivos

---

client/src/components/CarouselPromo.js

Pequeños cambios para que carrusel de descuentos muestre los de la base de datos.
Creo que se rompe el intervalo, y no se frena al pasar el mouse como parece indicar el evento creado en el primer useEffect.
Intenté hacerle algunas modificaciones pero veo que la librería usada tiene muchas particularidades y limitaciones. Creo que me tomaría mucho tiempo investigarla así que quizás es mejor que @AlejoMejia96 que ya la ha estado usando haga los cambios.
Alternativamente para sprint 3 podríamos rehacerla sin librería. Queda para debatir.

carrusel muestra descuentos de la db

---

client/src/Redux/Actions/actions.js
client/src/Redux/Reducers/HomeReducer.js
client/src/components/CardCart.js
client/src/components/CarouselCateg.js
client/src/components/Cart.js
client/src/components/CreateProducts.js
client/src/components/DropDownCategories.js
client/src/components/LoginComponent.js
client/src/components/NavBar.js
client/src/components/NavbarAdmin.js
client/src/components/ProductDetails/ProductDetails.js
client/src/components/commons/CartModal.js
client/src/components/commons/FavsModal.js
client/src/components/commons/LoginProfileButton.js
client/tailwind.config.js

Quedaron el carrito y favs del home funcionales, se puede agregar y quitar productos desde los mismos o ir a la ruta de cada uno, se puede comprar un producto en detail, faltaria que se pueda ver en el historial. Tambien cambie el naranja del home por uno mas fuerte apreciaria que me digan que les parece. Tambien limpie la consola y agregue notificaciones al añadir o sacar del carrito. Ahora avanzo con poder comprar en las rutas de wishlist y cart

Carrito home, compra detail, notificaciones, consola, color home

---

client/src/components/CardHistorial.js
client/src/components/Historial.js
client/src/components/Wishlist.js

historial component

---

client/src/components/CardCart.js
client/src/components/CardWishlist.js
client/src/components/Cart.js
client/src/components/Wishlist.js

No estaba andando el delete, solucionado

HotFix Delete /cart /wishlist

---

client/src/Redux/Actions/actions.js
client/src/Redux/Actions/types.js
client/src/Redux/Reducers/AdminReducer.js
client/src/components/ActivateDiscounts.js

Rompe algunas cosas para que tengamos que hacer mas hotfix antes de la demo.
(cambia todas las acciones, ahora hay una url base asi que en las acciones ya no ponemos mas la parte de "http:localhost:3001" sino que directamente dan eso por hecho y ponen por ejemplo "/products" solo)

Deploy changes

---

client/src/Redux/Actions/actions.js
client/src/components/CardWishlist.js
client/src/components/Home.js
client/src/components/LoginComponent.js
client/src/components/ProductDetails/ProductDetails.js

Reverts sebMar92/e-commerce-frontend#86

Revert "Me mamé"

---

client/src/components/CardCart.js
client/src/components/Cart.js

se ajusta el total de la cart y la direccion

Cart total

---

client/src/components/NavBar.js
client/src/components/NavbarAdmin.js
client/src/components/commons/SearchBar.js

Lo de la searchbar esta parcialmente arreglado, busca despues de 3 caracteres pero solo la primera vez. Luego empieza a buscar a partir de 1, estuve pensando un rato y no se me ocurrio asi que dejo ese pequeño fix para el que quiera manejarlo.

Searchbar busca despues de 3 caracteres y ahora muestra imagenes de producto, boton historial en home y responsive navbar admin

---

client/src/components/AdminPreview.js
client/src/components/CreateProducts.js
client/src/components/EditProducts.js
client/src/components/ProductDetails/ProductDetails.js

Preview de admin funcionando tal cual details.

Admin preview finish

---

client/src/components/Card.js
client/src/components/CardHome.js
client/src/components/CarouselCateg.js
client/src/components/ProductsByCategory.js

Arreglado error que no enviaba los datos del producto a wishlist/cart cuando se agregaban desde home o catálogo

Wishlist and Cart guest hotfix

---

client/src/components/AdminPreview.js
client/src/components/CreateProducts.js
client/src/components/EditProducts.js
client/src/components/NavBarEmpty.js
client/src/components/NavbarAdmin.js
client/src/components/commons/ButtonDiscard.js

responsive de create product y edit product
anadí un boton para descartar cambios en el edit product

create and edit product responsive

---

client/src/components/CreateProducts.js
client/src/components/EditProducts.js

Pequeños detalles en botones de cateogria, en formulario de creacion y edicion de producto

Detail form products

---

client/src/components/AdminAllUsers.js
client/src/components/commons/ModalConfirm.js

user Admin terminado edita rol y elimina user

Home admin

---

client/src/App.js
client/src/components/Footer/GeneralFooter.js
client/src/components/Profiles.js

component about us denominado profiles, alli esta nuestra info: nombres, fotos, links

contact us component

---

client/src/Redux/Actions/actions.js
client/src/Redux/Actions/interceptors.js
client/src/components/CarouselCateg.js
client/src/components/CarouselPromo.js
client/src/components/Footer/FooterHome.js
client/src/components/Skeletons/CardSkeleton.js
client/src/components/Skeletons/SkeletonArrow.js
client/src/components/Skeletons/SkeletonCarrousel.js

arregla errores de consola home

---

client/src/components/ProductDetails/ProductDetails.js

Botones controlados, para el caso guest, user sin stock y admin!

Control button buy pd finish

---

client/src/Redux/Actions/actions.js
client/src/components/CardWishlist.js
client/src/components/CarouselPromo.js
client/src/components/NavBar.js
client/src/components/ProductDetails/ProductDetails.js
client/src/components/Wishlist.js
client/src/components/commons/ButtonAddToCart.js

Arreglado botón de add to cart en el componente wishlist; ahora notifica al usuario al agregar al carrito.
Arreglos varios en la app.

Varios fix

---

client/src/Redux/Actions/actions.js
client/src/Redux/Actions/types.js
client/src/Redux/Reducers/HomeReducer.js
client/src/components/CardHistorial.js
client/src/components/Historial.js
client/src/components/Mercadopago/Checkout.js
client/src/components/Mercadopago/Failure.js
client/src/components/Mercadopago/OptionRender.js
client/src/components/PurchasePage.js

Arreglando cosas en mi bicicleta voy a casa de mi product manager a comprar mi ecommerce

Arreglamos muchas cosas 

---

client/src/components/ActivateDiscounts.js
client/src/components/AdminAllProducts.js
client/src/components/CardAdmin.js
client/src/components/CreateProducts.js
client/src/components/EditProducts.js
client/src/components/Footer/FooterHome.js
client/src/components/NavbarAdmin.js
client/src/components/NewsletterEdit.js
client/src/components/commons/LoginProfileButton.js

Create product no repeat

---

client/src/components/AdminProfile.js
client/src/components/ListOfOrders.js

se deja buscando por varios productos

listaOrders

---

client/src/components/commons/SearchBar.js

Se arreglo la Search Bar.
Te redirige con offset solo en los casos necesario.
Ya no queda clavada cuando se clickea estando en catalogo o product detail.

searchBarClosed&Offset
